version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/London"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/London"
    pull-request-branch-name:
      separator: "-"
